<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Villsource.Abp.Workflow</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Villsource.Abp.Workflow.Application\Villsource.Abp.Workflow.Application.csproj" />
    <ProjectReference Include="..\Villsource.Abp.Workflow.Domain.Tests\Villsource.Abp.Workflow.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

</Project>
